#!/usr/bin/env bash

# A script to install Godot and create a related .Desktop file

# Author: Dylan Emerson

: '
# Detect user distro
usr_os="abcd"

if [ -f /usr/lib/os-release ]; then
    . /usr/lib/os-release

    case $ID in
        ubuntu) usr_is="ubuntu"
            ;;
        debian) usr_os="debian"
            ;;
        arch) usr_os="arch"
            ;;
        *) echo "Unknown distro"
        ;;
    esac
fi
echo "Detected $usr_os based distro..."
'


# Default directories
script_dir=$( dirname "$(realpath $0)" )
godot_icon="$script_dir/Godot_icon.png"
icons_dir="$HOME/.icons/"
desktop_file_dir="$HOME/.local/share/applications/"

echo "Script path is $script_dir"

# Prompt user for Godot release version
read -p "Enter a stable release version of Godot (4.4.1, 4.3, etc): " version

# Define download archive URL with targeted release
filename="Godot_v$version-stable_linux.x86_64.zip"
download_url="https://github.com/godotengine/godot-builds/releases/download/$version-stable/$filename"
download_dir="Godot/$version-stable"

echo "Downloading Godot version $version-stable to ~/$download_dir..."

# Create download directory
cd ~/
mkdir -p "$download_dir"
cd "$download_dir" || exit 1

# Download Godot and verify installation
curl -LO "$download_url"

if [ ! -f "$filename" ];
then
    echo "Download failed. Please verify if version $version exists."
    exit 1
fi

# Unzip and remove zip file
unzip -o "$filename"
rm $filename

# Verify Godot exe exists and make it executable
godot_exe="Godot_v$version-stable_linux.x86_64"

if [ ! -f "$godot_exe" ]
then
    echo "Godot executable not found after extraction. Please try again."
    exit 1
fi

echo "Godot $version-stable successfully installed!"

# Make application entry directories if necessary
echo "Creating application directories (if they don't exist)..."
mkdir -p $desktop_file_dir
mkdir -p $icons_dir

# Create Desktop File
echo "Creating desktop file..."

echo "[Desktop Entry]
Type=Application
Name=Godot $version-stable
Comment=Godot desktop file generated by https://github.com/emersonds
Exec=$HOME/$download_dir/$godot_exe
Icon=$godot_icon
Terminal=false
Categories=Development;
Keywords=$filename;godot;development;programming" > "$desktop_file_dir$filename.desktop"

# Verify file was created
if [ ! -f "$desktop_file_dir$filename.desktop" ];
then
    echo "Unable to create file."
fi

# Change permissions of file to make it executable
chmod +x "$desktop_file_dir$filename.desktop"

# Copy icon to .icons folder so icon appears in application menu
cp $godot_icon $icons_dir

echo "Desktop file created successfully!"